packages:
    - "packages/*"

catalog:
    "@types/node": "24.13.2"
    esbuild-minify-templates: "0.13.1"
    eslint: "9.39.4"
    postcss: "8.5.15"
    tsx: "4.22.4"
    typescript: "6.0.3"
    vitest: "4.1.8"

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
    - "@navikt/*"

overrides:
    "@opentelemetry/core": "2.8.0"
    esbuild: "0.28.1"
    postcss: "8.5.15"
    shell-quote: "1.8.4"

engineStrict: true

allowBuilds:
    "@parcel/watcher": true
    esbuild: true
    husky: true
    less: true
    msw: true
    protobufjs: true
    sharp: true
    unrs-resolver: true
