apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nav-dekoratoren
  namespace: personbruker
  labels:
    team: personbruker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nav-dekoratoren
  minReplicas: 2
  maxReplicas: 40
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
