apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nav-dekoratoren-dev
  namespace: personbruker
  labels:
    team: personbruker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nav-dekoratoren-dev
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
