import type { StoryObj, Meta } from '@storybook/html';
import type { HeaderProps as ComplexHeaderProps } from '.';
import { ComplexHeader } from './complex-header';

const meta: Meta<ComplexHeaderProps> = {
  title: 'header/complex',
  tags: ['autodocs'],
  render: ComplexHeader,
};

export default meta;
type Story = StoryObj<ComplexHeaderProps>;

export const Default: Story = {
  args: {
    isNorwegian: true,
    mainMenu: [
      {
        displayName: 'Privatperson',
        path: 'https://www.nav.no',
        id: '9e6869d2-bf8c-4b64-8e7e-8bc2fc1c9ec7',
        children: [
          {
            displayName: 'Områder',
            path: '',
            flatten: true,
            id: '79173ea3-74cd-4d7a-a81f-a43915022c4e',
            children: [
              {
                displayName: 'Arbeid',
                path: '/arbeid',
                id: '433a7fcf-b5d4-47fa-b07b-2b388a968129',
                children: [],
              },
              {
                displayName: 'Helse og sykdom',
                path: '/helse',
                id: 'c0379053-4fdf-4151-8974-5d475449ebd2',
                children: [],
              },
              {
                displayName: 'Familie og barn',
                path: '/familie',
                id: 'e79dd1e5-e647-46a7-8387-a9a652ed022f',
                children: [],
              },
              {
                displayName: 'Pensjon',
                path: '/pensjon',
                id: '721f8cdb-f41b-4250-b7ea-f36f5bb2a558',
                children: [],
              },
              {
                displayName: 'Sosiale tjenester og veiledning',
                path: '/sosiale-tjenester',
                id: '67047b4c-9aad-403b-b86a-f86c439c5b7d',
                children: [],
              },
              {
                displayName: 'Hjelpemidler og tilrettelegging',
                path: '/hjelpemidler',
                id: '77c95b52-c6df-4d21-96f9-980b29bc4528',
                children: [],
              },
            ],
          },
          {
            displayName: 'Snarveier',
            path: '',
            flatten: false,
            id: 'c73650df-2e69-41e3-ae15-96ed90de4b0b',
            children: [
              {
                displayName: 'Søknad og skjema',
                path: '/soknader',
                flatten: false,
                id: '63294b4d-01e4-497b-b34c-ccdf0df3edf4',
                children: [],
              },
              {
                displayName: 'Ettersendelse',
                path: '/ettersende',
                flatten: false,
                id: 'a0f95de4-92a5-44f4-a361-65f7452fee06',
                children: [],
              },
              {
                displayName: 'Klage',
                path: '/klage',
                flatten: false,
                id: 'de30686a-5d55-4188-a735-bd0f5e6abab2',
                children: [],
              },
              {
                displayName: 'Pengestøtter og tjenester fra A til Å',
                path: '/tjenester',
                id: '4077b31a-0b92-48da-ac65-ec7f799b0aca',
                children: [],
              },
              {
                displayName: 'Saksbehandlingstider',
                path: '/saksbehandlingstider',
                id: '4d10e55b-ed4f-492a-9f07-dc8413f1ff7c',
                children: [],
              },
              {
                displayName: 'Utbetalinger',
                path: '/no/nav-og-samfunn/kontakt-nav/utbetalinger/utbetalinger',
                id: 'b3a2b780-1243-41b1-bd63-e47f014762a4',
                children: [],
              },
              {
                displayName: 'Satser',
                path: '/satser',
                flatten: false,
                id: '799aa2bd-3010-49f6-bd40-7a96d3ed1e98',
                children: [],
              },
              {
                displayName: 'Meldekort',
                path: '/no/person/arbeid/dagpenger-ved-arbeidsloshet-og-permittering/meldekort-hvordan-gjor-du-det',
                id: 'bcd4d2ab-de95-4904-9cf2-476652dd0150',
                children: [],
              },
              {
                displayName: 'Kurs fra NAV',
                path: '/no/nav-og-samfunn/kontakt-nav/kurs-fra-nav',
                id: 'e0b328f5-f509-4fd8-879d-79679b3b1667',
                children: [],
              },
              {
                displayName: 'Feiltolkning av EØS-reglene',
                path: '/no/nav-og-samfunn/kontakt-nav/feiltolkning-av-eos-reglene',
                flatten: false,
                id: '0ef10379-91d0-4be6-abb2-75be206b1ad1',
                children: [],
              },
            ],
          },
        ],
        isActive: true,
      },
      {
        displayName: 'Arbeidsgiver',
        path: '/no/bedrift',
        id: 'b9fb1110-22c1-44a5-81a5-74336d82ccb7',
        children: [
          {
            displayName: 'Sykdom, skade og fravær',
            path: '/no/bedrift/oppfolging',
            flatten: false,
            id: '72a34ff7-2644-4dcd-9921-39a20bcf9ed7',
            children: [
              {
                displayName: 'Ansatt er sykmeldt',
                path: '/arbeidsgiver/sykmeldt-ansatt',
                flatten: false,
                id: '108c225e-bcec-43de-a553-7ad91433284e',
                children: [],
              },
              {
                displayName:
                  'Vil redusere sykefravær og beholde ansatte i jobb',
                path: '/arbeidsgiver/redusere-sykefravar',
                flatten: false,
                id: '4f24e3a7-ec73-481d-b74b-c7455d039bc6',
                children: [],
              },
              {
                displayName:
                  'Ansatt har blitt syk eller skadet på arbeidsplassen',
                path: '/arbeidsgiver/yrkesskade',
                flatten: false,
                id: '8c6f87b3-d582-48c8-9a5e-1d4fd01d2903',
                children: [],
              },
              {
                displayName: 'Ansatt har sykdom i familien',
                path: '/arbeidsgiver/sykdom-i-familien',
                id: '8857a661-e41e-4fcf-9337-2a18236c1b9e',
                children: [],
              },
              {
                displayName: 'Ansatt venter barn',
                path: '/arbeidsgiver/ansatt-venter-barn',
                flatten: false,
                id: '5f60a33d-626e-43bd-82b2-e0876f89a45d',
                children: [],
              },
              {
                displayName: 'Sykefraværsstatistikk',
                path: 'https://arbeidsgiver.nav.no/sykefravarsstatistikk/',
                id: '017271da-1f66-448e-875d-360675b544ee',
                children: [],
              },
            ],
          },
          {
            displayName: 'Rekruttere og inkludere',
            path: '/no/bedrift/rekruttering',
            flatten: false,
            id: 'cb2997f9-edb4-48c4-9e21-2d345f4ae1a0',
            children: [
              {
                displayName: 'Annonser stillinger eller finn kandidater',
                path: 'https://arbeidsplassen.nav.no/bedrift',
                flatten: false,
                id: '620b8d91-1be4-4654-8bca-723d21bc57dc',
                children: [],
              },
              {
                displayName: 'Vil hjelpe flere inn i arbeidslivet',
                path: '/arbeidsgiver/inkludere',
                flatten: false,
                id: 'ea03eafc-c107-49b7-af01-2309762af65e',
                children: [],
              },
              {
                displayName: 'Vil rekruttere',
                path: '/arbeidsgiver/rekruttere',
                flatten: false,
                id: '92809261-cacb-4802-bae5-4af7b8833170',
                children: [],
              },
              {
                displayName: 'Lønnstilskudd',
                path: '/arbeidsgiver/midlertidig-lonnstilskudd',
                flatten: false,
                id: 'c92331ec-5c06-4125-9d64-f44f86ff4be0',
                children: [],
              },
            ],
          },
          {
            displayName: 'Permittere og nedbemanne',
            path: '/nav.no-ressurser/filer/bedrift/permittering-og-omstilling',
            flatten: false,
            id: 'fd830811-1371-48d0-a5a5-04c47b4609d8',
            children: [
              {
                displayName: 'Meld fra til NAV',
                path: 'https://arbeidsgiver.nav.no/permittering/',
                id: '5ec73cb2-6061-4739-b515-44e8919354cb',
                children: [],
              },
              {
                displayName: 'Permittere eller nedbemanne',
                path: '/arbeidsgiver/permittere-nedbemanne',
                flatten: false,
                id: '4e8d1cce-7bd6-403a-8cbc-8923b58ea2c8',
                children: [],
              },
            ],
          },
          {
            displayName: 'Skjemaer, tilganger og refusjoner',
            path: '/no/bedrift/tjenester-og-skjemaer',
            flatten: false,
            id: '6132488e-d40f-4729-abe4-afc9b0baed2d',
            children: [
              {
                displayName: 'Søknad og skjema',
                path: '/arbeidsgiver/soknader',
                flatten: false,
                id: '75f3d1af-30ff-4496-a1a9-e49223eb0528',
                children: [],
              },
              {
                displayName: 'Saksbehandlingstider',
                path: '/arbeidsgiver/saksbehandlingstider',
                flatten: false,
                id: 'f097ff97-9e27-4df7-8ce0-2dd082a9d4e3',
                children: [],
              },
              {
                displayName: 'Klage',
                path: '/arbeidsgiver/klage',
                flatten: false,
                id: '5f1cdae4-02cd-4608-ab16-e7dc16ef7c05',
                children: [],
              },
              {
                displayName: 'Altinn-rettigheter til NAVs tjenester',
                path: '/arbeidsgiver/tilganger',
                flatten: false,
                id: '5e5d17d2-7b64-45e6-953a-68743970a68b',
                children: [],
              },
              {
                displayName: 'Inntektsmelding, rapporter m.m.',
                path: '/arbeidsgiver/rapporter',
                flatten: false,
                id: 'c4240b0e-5413-4ffa-bc2d-6f5f857d6667',
                children: [],
              },
              {
                displayName: 'Forsikring for næringsdrivende m.fl.',
                path: '/no/bedrift/tjenester-og-skjemaer/selvstendig-naringsdrivende-med-flere',
                flatten: false,
                id: '5dad03e4-d2c3-4245-a2d7-caecac0c3718',
                children: [],
              },
              {
                displayName: 'Aa-registeret',
                path: '/no/bedrift/tjenester-og-skjemaer/aa-registeret-og-a-meldingen',
                id: '847513c4-d85e-46cd-aca5-ad00f78a30d2',
                children: [],
              },
            ],
          },
        ],
        isActive: false,
      },
      {
        displayName: 'Samarbeidspartner',
        path: '',
        id: '5942d16e-8ab2-490c-900d-99ba80ffe6e5',
        children: [
          {
            displayName: 'Rolle',
            path: '',
            flatten: false,
            id: '62eabdb7-3e3b-4e98-937b-20e011fcde94',
            children: [
              {
                displayName: 'Leger og andre behandlere',
                path: '/no/nav-og-samfunn/samarbeid/leger-og-andre-behandlere',
                id: '763009d7-a071-4fda-8602-599b5aab44ae',
                children: [],
              },
              {
                displayName: 'Tiltaksarrangør',
                path: '/samarbeidspartner/tiltaksarrangor',
                flatten: false,
                id: 'c0e35520-c911-444c-a67c-46d2d25ff602',
                children: [],
              },
              {
                displayName: 'Hjelpemiddelformidler',
                path: '/no/nav-og-samfunn/samarbeid/hjelpemidler',
                flatten: false,
                id: '3a48480b-8cf5-4e9b-8255-486e48f9d5b4',
                children: [],
              },
              {
                displayName: 'Bostyrer',
                path: '/samarbeidspartner/bostyrer',
                flatten: false,
                id: '80eb6ff3-3d18-4fc1-bada-a5c65d6c3b2b',
                children: [],
              },
              {
                displayName:
                  'Ansatt i NAV-kontor, kommunen eller fylkeskommunen',
                path: '/no/nav-og-samfunn/samarbeid/for-kommunen',
                flatten: false,
                id: '175cf6ee-2ab3-41f0-b748-acac59674406',
                children: [],
              },
              {
                displayName: 'Tillitsvalgt eller verneombud',
                path: '/samarbeidspartner/tillitsvalgt-verneombud',
                flatten: false,
                id: '51ae4003-0e6e-4611-9b07-9c5b6b1a930d',
                children: [],
              },
            ],
          },
          {
            displayName: 'På tvers',
            path: '/no/nav-og-samfunn/samarbeid',
            id: 'ad8ea002-9006-4109-97d3-6694cf74a24a',
            children: [
              {
                displayName: 'Søknad og skjema',
                path: '/samarbeidspartner/soknader',
                flatten: false,
                id: 'd27043f4-d7f8-4d9a-a16e-464989262056',
                children: [],
              },
              {
                displayName: 'Tilskudd gjennom NAV',
                path: '/no/nav-og-samfunn/samarbeid/tilskudd-gjennom-nav',
                id: 'abfbc074-1d42-4729-a977-efcf1c06f012',
                children: [],
              },
              {
                displayName: 'Arbeid, psykisk helse og samarbeidspartnere',
                path: '/no/nav-og-samfunn/samarbeid/arbeid-og-psykisk-helse',
                id: '7aacb881-6008-4404-9d71-c89297fb018a',
                children: [],
              },
              {
                displayName: 'Arbeidslivskriminalitet og trygdesvindel',
                path: '/no/nav-og-samfunn/samarbeid/arbeidslivskriminalitet-og-trygdesvindel',
                id: 'bc89de77-54a3-4575-b96e-768ab6719a3c',
                children: [],
              },
              {
                displayName: 'Brukermedvirkning',
                path: '/samarbeidspartner/brukermedvirkning',
                flatten: false,
                id: '76cb9ada-a525-4b01-81cc-6251d0ebbc82',
                children: [],
              },
            ],
          },
        ],
        isActive: false,
      },
    ],
    headerMenuLinks: [
      {
        displayName: 'Områder',
        path: '',
        flatten: true,
        id: '79173ea3-74cd-4d7a-a81f-a43915022c4e',
        children: [
          {
            displayName: 'Arbeid',
            path: '/arbeid',
            id: '433a7fcf-b5d4-47fa-b07b-2b388a968129',
            children: [],
          },
          {
            displayName: 'Helse og sykdom',
            path: '/helse',
            id: 'c0379053-4fdf-4151-8974-5d475449ebd2',
            children: [],
          },
          {
            displayName: 'Familie og barn',
            path: '/familie',
            id: 'e79dd1e5-e647-46a7-8387-a9a652ed022f',
            children: [],
          },
          {
            displayName: 'Pensjon',
            path: '/pensjon',
            id: '721f8cdb-f41b-4250-b7ea-f36f5bb2a558',
            children: [],
          },
          {
            displayName: 'Sosiale tjenester og veiledning',
            path: '/sosiale-tjenester',
            id: '67047b4c-9aad-403b-b86a-f86c439c5b7d',
            children: [],
          },
          {
            displayName: 'Hjelpemidler og tilrettelegging',
            path: '/hjelpemidler',
            id: '77c95b52-c6df-4d21-96f9-980b29bc4528',
            children: [],
          },
        ],
      },
      {
        displayName: 'Snarveier',
        path: '',
        flatten: false,
        id: 'c73650df-2e69-41e3-ae15-96ed90de4b0b',
        children: [
          {
            displayName: 'Søknad og skjema',
            path: '/soknader',
            flatten: false,
            id: '63294b4d-01e4-497b-b34c-ccdf0df3edf4',
            children: [],
          },
          {
            displayName: 'Ettersendelse',
            path: '/ettersende',
            flatten: false,
            id: 'a0f95de4-92a5-44f4-a361-65f7452fee06',
            children: [],
          },
          {
            displayName: 'Klage',
            path: '/klage',
            flatten: false,
            id: 'de30686a-5d55-4188-a735-bd0f5e6abab2',
            children: [],
          },
          {
            displayName: 'Pengestøtter og tjenester fra A til Å',
            path: '/tjenester',
            id: '4077b31a-0b92-48da-ac65-ec7f799b0aca',
            children: [],
          },
          {
            displayName: 'Saksbehandlingstider',
            path: '/saksbehandlingstider',
            id: '4d10e55b-ed4f-492a-9f07-dc8413f1ff7c',
            children: [],
          },
          {
            displayName: 'Utbetalinger',
            path: '/no/nav-og-samfunn/kontakt-nav/utbetalinger/utbetalinger',
            id: 'b3a2b780-1243-41b1-bd63-e47f014762a4',
            children: [],
          },
          {
            displayName: 'Satser',
            path: '/satser',
            flatten: false,
            id: '799aa2bd-3010-49f6-bd40-7a96d3ed1e98',
            children: [],
          },
          {
            displayName: 'Meldekort',
            path: '/no/person/arbeid/dagpenger-ved-arbeidsloshet-og-permittering/meldekort-hvordan-gjor-du-det',
            id: 'bcd4d2ab-de95-4904-9cf2-476652dd0150',
            children: [],
          },
          {
            displayName: 'Kurs fra NAV',
            path: '/no/nav-og-samfunn/kontakt-nav/kurs-fra-nav',
            id: 'e0b328f5-f509-4fd8-879d-79679b3b1667',
            children: [],
          },
          {
            displayName: 'Feiltolkning av EØS-reglene',
            path: '/no/nav-og-samfunn/kontakt-nav/feiltolkning-av-eos-reglene',
            flatten: false,
            id: '0ef10379-91d0-4be6-abb2-75be206b1ad1',
            children: [],
          },
        ],
      },
    ],
    innlogget: false,
    breadcrumbs: [],
    utilsBackground: 'transparent',
    availableLanguages: [],
    myPageMenu: [
      {
        displayName: 'Din oversikt',
        path: '',
        id: '87902576-3ce1-48bb-88bd-798d04352984',
        children: [
          {
            displayName: 'Dokumentarkiv',
            path: 'https://person.nav.no/mine-saker',
            flatten: false,
            id: '15e2dca8-a68c-484a-b7fe-5ec9fe7ed7bb',
            children: [],
          },
          {
            displayName: 'Din innboks',
            path: 'https://innboks.nav.no/',
            id: '79ae75ad-7473-4414-b411-129151107f4b',
            children: [],
          },
          {
            displayName: 'Dine utbetalinger',
            path: 'https://tjenester.nav.no/utbetalingsoversikt/',
            id: '2462c7e9-6497-4d5d-bb05-d129a3f599d5',
            children: [],
          },
          {
            displayName: 'Endre kontonummer/adresse',
            path: '/person/personopplysninger/nb/#utbetaling',
            id: '43783128-3ebb-44c9-aec4-3d8a6b2e457d',
            children: [],
          },
          {
            displayName: 'Send ny søknad',
            path: '/soknader',
            id: '5e691c9d-9943-439c-b36e-f8691a774629',
            children: [],
          },
          {
            displayName: 'Ettersend vedlegg',
            path: '/ettersendelse',
            id: 'f357124c-f599-42d9-85de-b02563fd09c0',
            children: [],
          },
          {
            displayName: 'Send beskjed til NAV',
            path: '/person/kontakt-oss/',
            id: 'b9f87d61-967a-46fa-95e6-395824252644',
            children: [],
          },
          {
            displayName: 'Personopplysninger',
            path: '/person/personopplysninger',
            id: '29bb2934-dc1b-44fe-9349-f427243fcd76',
            children: [],
          },
        ],
      },
      {
        displayName: 'Arbeid',
        path: '',
        id: 'a6d04c66-3f5b-431f-8db3-420b25aa3a75',
        children: [
          {
            displayName: 'Registrer deg som arbeidssøker',
            path: 'https://www.nav.no/arbeid/registrering/',
            id: 'd01301f4-e83d-4358-9ef7-4184c00c52bd',
            children: [],
          },
          {
            displayName: 'Send meldekort',
            path: '/meldekort/',
            id: '6f75ca5c-0736-4cb3-95b2-fb2565ac73ae',
            children: [],
          },
          {
            displayName: 'Finn ledige stillinger',
            path: 'https://arbeidsplassen.nav.no/stillinger',
            id: 'd1500b8b-7afa-429c-8b52-e48c73e24c2d',
            children: [],
          },
          {
            displayName: 'Din CV',
            path: 'https://arbeidsplassen.nav.no/minside',
            id: 'd10cdf61-dfa3-4d4a-a0ef-60cbec525ab4',
            children: [],
          },
          {
            displayName: 'Dine lagrede søk',
            path: 'https://arbeidsplassen.nav.no/stillinger/lagrede-sok',
            id: '7e06bac1-81d7-4f22-a1ae-1ba41502b802',
            children: [],
          },
          {
            displayName: 'Din aktivitetsplan',
            path: 'https://aktivitetsplan.nav.no',
            id: 'df13e0c0-ab47-4bd8-9593-7a5dca7986d6',
            children: [],
          },
          {
            displayName: 'Dialog med veilederen din',
            path: 'http://nav.no/arbeid/dialog',
            id: 'b2041cba-9580-499e-815b-caa624d49304',
            children: [],
          },
          {
            displayName: 'Ditt jobbspor',
            path: 'https://jobbsporet.nav.no/',
            flatten: false,
            id: '563ff36c-cd2e-4bd3-9a9d-b314562774be',
            children: [],
          },
        ],
      },
      {
        displayName: 'Flere tjenester',
        path: '',
        id: 'ecfbac87-4259-4402-8f64-6c65b2ed2dfd',
        children: [
          {
            displayName: 'Din pensjon',
            path: 'https://www.nav.no/pselv/publisering/dinpensjon.jsf?context=pensjon',
            id: 'bfe43e1e-a074-4300-a480-618ac9b054f6',
            children: [],
          },
          {
            displayName: 'Din uføretrygd',
            path: 'https://www.nav.no/pselv/publisering/uforetrygd.jsf?context=ut',
            id: '02f4c191-dee0-43e9-acff-c05d8b9aec10',
            children: [],
          },
          {
            displayName: 'Ditt sykefravær',
            path: 'https://www.nav.no/syk/sykefravaer',
            id: 'd5c02d97-3041-4c72-9555-993efb7605b0',
            children: [],
          },
          {
            displayName: 'Dine foreldrepenger',
            path: 'https://foreldrepenger.nav.no',
            id: '7c5a5ff5-c06e-4279-ab85-e9a87f9743c2',
            children: [],
          },
          {
            displayName: 'Dine fullmakter',
            path: 'https://www.nav.no/person/pdl-fullmakt-ui',
            id: 'ff549cdc-c3ac-4056-8838-c3a01cf8b086',
            children: [],
          },
          {
            displayName: 'Dine pleiepenger',
            path: 'https://www.nav.no/familie/sykdom-i-familien/soknad/innsyn',
            id: '1c79a492-9ba7-42af-b29d-c18a5dee2367',
            children: [],
          },
          {
            displayName: 'Dine hjelpemidler',
            path: 'https://www.nav.no/hjelpemidler/dinehjelpemidler/',
            id: '172fae26-2e5c-4442-b9f5-fcb276fe9ad5',
            children: [],
          },
          {
            displayName: 'Økonomisk sosialhjelp',
            path: 'https://www.nav.no/sosialhjelp/innsyn/',
            id: '97e23fef-f3d8-4861-a3d5-aac395477037',
            children: [],
          },
        ],
      },
    ],
    texts: {
      share_screen: 'Del skjerm med veileder',
      to_top: 'Til toppen',
      menu: 'Meny',
      close: 'Lukk',
      did_you_find: 'Fant du det du lette etter?',
      search: 'Søk',
      sok_knapp_sokefelt: 'Søk på nav.no',
      login: 'Logg inn',
      logout: 'Logg ut',
      notifications: 'Varsler',
      notifications_empty_list: 'Du har ingen nye varsler',
      notifications_empty_list_description: 'Vi varsler deg når noe skjer',
      notifications_show_all: 'Tidligere varsler',
      notifications_messages_title: 'Beskjeder',
      notified_EPOST: 'Varslet på e-post',
      notified_SMS: 'Varslet på SMS',
      earlier_notifications: 'Tidligere varsler',
      masked_message_text:
        'Du har fått en melding, logg inn med høyere sikkerhetsnivå for å se meldingen.',
      masked_task_text:
        'Du har fått en oppgave, logg inn med høyere sikkerhetsnivå for å se oppgaven.',
      archive: 'Arkiver',
      notifications_tasks_title: 'Oppgaver',
      token_warning_title: 'Du blir snart logget ut automatisk',
      token_warning_body: 'Vil du fortsatt være innlogget?',
      session_warning_title: 'Du blir logget ut automatisk om ca $1 minutter',
      session_warning_body: 'Avslutt det du jobber med og logg inn igjen.',
      yes: 'Ja',
      no: 'Nei',
      ok: 'OK',
      hensikt_med_tilbakemelding:
        'Du får dessverre ikke svar på tilbakemeldingen din. Har du spørsmål eller trenger du hjelp?',
      hensikt_med_tilbakemelding_lenke: 'Ring, chat eller skriv til oss',
      send_undersokelse_takk: 'Takk!',
      loading_notifications: 'Laster varslinger',
      notifications_error: 'Feil ved lasting av varsler',
    },
  },
};
