name: Dependabot lockfile fix
on:
  pull_request:
    branches: [main]
    paths:
      - pnpm-workspace.yaml
      - package.json
      - "**/package.json"

permissions:
  contents: write

jobs:
  update-lockfile:
    uses: navikt/navno-ci/.github/workflows/dependabot-lockfile.yml@v1
    secrets: inherit
