name: Deploy network policy to Nais
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .nais/network-policy.yml

jobs:
  deploy-network-policy:
    name: Deploy network policy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/network-policy.yml
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/network-policy.yml
