name: Deploy to prod
on:
  push:
    branches: [main]
    paths-ignore: ['**.md']

jobs:
  deploy:
    uses: ./.github/workflows/build-deploy-prod.yml
    permissions: { contents: read, id-token: write }
    secrets: inherit

  release:
    needs: deploy
    uses: navikt/navno-ci/.github/workflows/release.yml@v1
    permissions: { contents: write }
    secrets: inherit
