name: Deploy to Team Min Side beta
on:
  workflow_dispatch:
    inputs:
      DEPLOY_INTERNAL:
        description: "Deploy previous version to internal"
        required: false
        type: boolean
      SKIP_TESTS:
        description: "Skip tests"
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      IMAGE: ${{ steps.build_test.outputs.IMAGE }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build and test
        id: build_test
        uses: ./.github/actions/build-test
        with:
          READER_TOKEN: ${{ secrets.READER_TOKEN }}
          IMAGE_SUFFIX: dev-beta-tms
          SKIP_TESTS: ${{ inputs.SKIP_TESTS }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Nais
        uses: ./.github/actions/deploy-to-nais
        with:
          DEPLOY_INSTANCE: dev-beta-tms
          CLUSTER: dev-gcp
          IMAGE: ${{ needs.build.outputs.IMAGE }}
          DEPLOY_INTERNAL: ${{ inputs.DEPLOY_INTERNAL }}
          VARS_UPDATE_TOKEN: ${{ secrets.VARS_UPDATE_TOKEN }}
