name: Deploy to dev
on:
  workflow_dispatch:
    inputs:
      DEPLOY_INTERNAL:
        description: "Deploy previous version to internal"
        required: false
        type: boolean
      SKIP_TESTS:
        description: "Skip tests"
        required: false
        type: boolean

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    permissions:
      id-token: write
      contents: read
    with:
      IMAGE_SUFFIX: dev-stable
      SKIP_TESTS: ${{ inputs.SKIP_TESTS }}
    secrets: inherit
  deploy:
    uses: ./.github/workflows/deploy-application.yml
    needs: build
    permissions:
      id-token: write
      contents: read
    with:
      DEPLOY_INSTANCE: dev-stable
      CLUSTER: dev-gcp
      IMAGE: ${{ needs.build.outputs.IMAGE }}
      DEPLOY_INTERNAL: ${{ inputs.DEPLOY_INTERNAL }}
      HPA_FILE: hpa-dev-stable.yml
    secrets:
      VARS_UPDATE_TOKEN: ${{ secrets.VARS_UPDATE_TOKEN }}
