name: Deploy to Team Nav.no dev2/beta
on:
  workflow_dispatch:
    inputs:
      DEPLOY_PREVIOUS:
        description: 'Deploy previous version to internal'
        required: false
        type: boolean
      SKIP_TESTS:
        description: 'Skip Playwright tests'
        required: false
        type: boolean
        default: true

jobs:
  build:
    uses: navikt/navno-ci/.github/workflows/node-build.yml@v1
    permissions: { contents: read, id-token: write }
    with:
      team: personbruker
      image-suffix: dev-beta-navno
      image-tag: latest
      platforms: linux/amd64,linux/arm64
      cdn-source: ./packages/server/public
      cdn-destination: /nav-dekoratoren
      prune-remove: ''
      playwright: ${{ !inputs.SKIP_TESTS && 'pnpm run test:e2e' || '' }}
    secrets: inherit

  network-policy:
    needs: build
    uses: navikt/navno-ci/.github/workflows/nais-deploy.yml@v1
    permissions: { contents: read, id-token: write }
    with:
      cluster: dev-gcp
      resource: .nais/network-policy.yml

  deploy:
    needs: [build, network-policy]
    uses: ./.github/workflows/deploy-instance.yml
    permissions: { contents: read, id-token: write }
    with:
      instance: dev-beta-navno
      cluster: dev-gcp
      image: ${{ needs.build.outputs.image }}
      deploy-previous: ${{ inputs.DEPLOY_PREVIOUS }}
    secrets: inherit
