name: Run tests on PR
on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-test:
    uses: navikt/navno-ci/.github/workflows/node-build.yml@v1
    with:
      push-image: false
      team: personbruker
      playwright: pnpm run test:e2e
    secrets: inherit
